export const CustomErrors = {
  userNotFound: 'User not found',
  invalidLogin: 'Invalid login',
  invalidLoginIsEmail: 'Use your username to login',
  invalidLoginBadUsername: 'Incorrect Username',
  invalidLoginBadPassword: 'Incorrect Password',
  invalidEmailFormat_Small: 'Email too small',
  invalidEmailFormat_Long: 'Email too long',
  invalidEmail: 'Invalid email',
  invalidPasswordFormat_Small: 'Password too small',
  invalidPasswordFormat_Long: 'Password too long',
  invalidPassword: 'Invalid password',
  invalidUsernameFormat_Small: 'Username too small',
  invalidUsernameFormat_Long: 'Username too long',
  invalidUsername: 'Invalid Username',
  wrongOldPass: 'Wrong old password',
  notSignedIn: 'You are not logged in!',
  tooManyAccounts: 'Too many account',
  noCharSelected: 'No Character Selected',
  alreadyActivated: 'Already Activated',
};
